#!/usr/bin/env bash
# active firewall to allow 3 ports only
sudo ufw default deny incoming
sudo ufw allow 80/tcp
sudo ufw allow 5001/tcp
sudo ufw allow 443/tcp
sudo ufw allow 22/tcp
sudo ufw disable
sudo ufw enable
